/* libglycin-gtk4-1.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "GlyGtk4", gir_namespace = "GlyGtk4", gir_version = "1", lower_case_cprefix = "gly_gtk_")]
namespace GlyGtk4 {
	[CCode (cheader_filename = "glycin-gtk4.h")]
	[Version (since = "1.0")]
	public static Gdk.Texture frame_get_texture (Gly.Frame frame);
}
